const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DATA={events:'data/events.json',students:'data/students.json',faqs:'data/faqs.json'};
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function initTheme(){const saved=localStorage.getItem('studenthub-theme')||'light';document.documentElement.dataset.theme=saved;const b=$('#themeBtn');if(b)b.textContent=saved==='dark'?'☀️':'🌙';b?.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('studenthub-theme',next);b.textContent=next==='dark'?'☀️':'🌙';toast(`${next==='dark'?'Dark':'Light'} mode enabled`)});}
function initMenu(){const menu=$('#menuBtn'),side=$('#sidebar');menu?.addEventListener('click',()=>{side?.classList.toggle('open');const open=side?.classList.contains('open');menu.setAttribute('aria-expanded',open?'true':'false')});$$('.side-link').forEach(a=>a.addEventListener('click',()=>side?.classList.remove('open')))}
function initNotice(){const n=$('#notice');$('#noticeClose')?.addEventListener('click',()=>{n?.classList.add('hidden');sessionStorage.setItem('noticeClosed','1')});if(sessionStorage.getItem('noticeClosed'))n?.classList.add('hidden')}
function initModal(){const m=$('#modal'),open=$('#openModal');open?.addEventListener('click',()=>m?.classList.add('show'));$$('[data-close-modal]').forEach(x=>x.addEventListener('click',()=>m?.classList.remove('show')));m?.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')})}
function initSlider(){const slides=$$('.slide');if(!slides.length)return;let i=0;const show=n=>{i=(n+slides.length)%slides.length;slides.forEach((s,k)=>s.classList.toggle('active',k===i))};$('#prevSlide')?.addEventListener('click',()=>show(i-1));$('#nextSlide')?.addEventListener('click',()=>show(i+1));setInterval(()=>show(i+1),5000)}
async function fetchJSON(key){try{const r=await fetch(DATA[key]);if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch(e){console.error(e);toast('Could not load '+key+'. Run the folder with a local server.');return[]}}
async function renderFaqs(){const box=$('#faqList');if(!box)return;box.innerHTML='<div class="loading">Loading FAQs…</div>';const data=await fetchJSON('faqs');if(!data.length){box.innerHTML='<div class="empty">No FAQs available.</div>';return}box.innerHTML=data.map((x,i)=>`<div class="faq-item"><button class="faq-q" aria-expanded="false">${x.question}<span>+</span></button><div class="faq-a">${x.answer}</div></div>`).join('');$$('.faq-q',box).forEach(b=>b.addEventListener('click',()=>{const item=b.parentElement;item.classList.toggle('open');b.setAttribute('aria-expanded',item.classList.contains('open'));b.querySelector('span').textContent=item.classList.contains('open')?'−':'+'}))}
function passwordStrength(v){let n=0;if(v.length>=8)n++;if(/[A-Z]/.test(v))n++;if(/[a-z]/.test(v))n++;if(/\d/.test(v))n++;if(/[^A-Za-z0-9]/.test(v))n++;return n}
function validateRegistration(){const form=$('#registerForm');if(!form)return;const fields=['name','email','mobile','password','confirmPassword','course','year','gender'];const err=k=>$('#err-'+k);const clear=()=>fields.forEach(k=>{if(err(k))err(k).textContent=''});const valid=()=>{clear();let ok=true;const name=$('#name').value.trim(),email=$('#email').value.trim(),mobile=$('#mobile').value.trim(),pass=$('#password').value,cp=$('#confirmPassword').value;if(!/^[A-Za-z ]{2,40}$/.test(name)){err('name').textContent='Use 2–40 letters and spaces only.';ok=false}if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)){err('email').textContent='Enter a valid email address.';ok=false}if(!/^[6-9]\d{9}$/.test(mobile)){err('mobile').textContent='Enter a valid 10-digit Indian mobile number.';ok=false}if(!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,20}$/.test(pass)){err('password').textContent='8–20 chars with uppercase, lowercase, number and symbol.';ok=false}if(pass!==cp){err('confirmPassword').textContent='Passwords do not match.';ok=false}if(!$('#course').value){err('course').textContent='Select a course.';ok=false}if(!$('#year').value){err('year').textContent='Select a year.';ok=false}if(!$('input[name="gender"]:checked')){err('gender').textContent='Select gender.';ok=false}if(!$('#terms').checked){err('terms').textContent='Accept the terms to continue.';ok=false}return ok};form.addEventListener('submit',e=>{e.preventDefault();if(valid()){localStorage.setItem('studenthub-user',JSON.stringify({name:$('#name').value.trim(),email:$('#email').value.trim(),course:$('#course').value,year:$('#year').value}));toast('Registration successful! Redirecting…');setTimeout(()=>location.href='login.html',700)}});$('#password')?.addEventListener('input',e=>{const n=passwordStrength(e.target.value),bar=$('#strengthBar');if(bar){bar.style.width=(n*20)+'%';bar.title=['','Very weak','Weak','Fair','Good','Strong'][n]}});}
function initLogin(){const f=$('#loginForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const email=$('#loginEmail').value.trim(),pass=$('#loginPassword').value;let ok=true;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){$('#loginEmailErr').textContent='Enter a valid email.';ok=false}else $('#loginEmailErr').textContent='';if(pass.length<6){$('#loginPassErr').textContent='Password must be at least 6 characters.';ok=false}else $('#loginPassErr').textContent='';if(ok){localStorage.setItem('studenthub-auth','1');const u=JSON.parse(localStorage.getItem('studenthub-user')||'{}');if(!u.name)localStorage.setItem('studenthub-user',JSON.stringify({name:email.split('@')[0],email}));location.href='deskboard.html'}})}
function protect(){if(document.body.dataset.protected==='true'&&localStorage.getItem('studenthub-auth')!=='1')location.href='login.html'}
function initLogout(){$('#logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem('studenthub-auth');location.href='index.html'})}
function renderUser(){const u=JSON.parse(localStorage.getItem('studenthub-user')||'{}');$$('[data-user-name]').forEach(x=>x.textContent=u.name||'Student');$$('[data-user-email]').forEach(x=>x.textContent=u.email||'student@example.com')}
function setupDataPage(){const type=document.body.dataset.dataPage;if(!type)return;const tbody=$('#dataBody'),search=$('#search'),filter=$('#filter'),sort=$('#sort'),pager=$('#pagination'),loading=$('#dataLoading');let all=[],page=1;const per=6;const draw=()=>{let d=[...all];const q=(search?.value||'').toLowerCase();if(q)d=d.filter(x=>JSON.stringify(x).toLowerCase().includes(q));const fv=filter?.value;if(fv&&fv!=='all')d=d.filter(x=>Object.values(x).some(v=>String(v).toLowerCase()===fv.toLowerCase()));const sv=sort?.value;if(sv){d.sort((a,b)=>String(a[sv]??'').localeCompare(String(b[sv]??''),undefined,{numeric:true,sensitivity:'base'}))}const pages=Math.max(1,Math.ceil(d.length/per));if(page>pages)page=pages;const rows=d.slice((page-1)*per,page*per);tbody.innerHTML=rows.length?rows.map(row=>`<tr>${Object.values(row).map(v=>`<td>${v}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="20" class="empty">No matching records.</td></tr>`;pager.innerHTML=Array.from({length:pages},(_,i)=>`<button class="page-btn ${i+1===page?'active':''}" data-p="${i+1}">${i+1}</button>`).join('');$$('.page-btn',pager).forEach(b=>b.addEventListener('click',()=>{page=+b.dataset.p;draw()}));$('#recordCount').textContent=`${d.length} records`;};
(async()=>{loading.hidden=false;all=await fetchJSON(type);loading.hidden=true;if(type==='events'&&filter){[...new Set(all.map(x=>x.category))].forEach(v=>filter.insertAdjacentHTML('beforeend',`<option>${v}</option>`))}if(sort){const keys=all[0]?Object.keys(all[0]):[];sort.innerHTML='<option value="">Sort by…</option>'+keys.map(k=>`<option value="${k}">${k}</option>`).join('')}draw()})();search?.addEventListener('input',()=>{page=1;draw()});filter?.addEventListener('change',()=>{page=1;draw()});sort?.addEventListener('change',()=>{page=1;draw()})}
document.addEventListener('DOMContentLoaded',()=>{protect();initTheme();initMenu();initNotice();initModal();initSlider();renderFaqs();validateRegistration();initLogin();initLogout();renderUser();setupDataPage();$$('[data-demo]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.demo)));});
